import type { Question } from "./types";

export const BANK: Question[] = [
  {
    id: "q-mat-01",
    subjectId: "mat",
    skill: "álgebra",
    difficulty: 1,
    type: "opcion",
    prompt: "Resuelve 2x + 5 = 17. ¿Cuál es el valor de x?",
    options: ["4", "5", "6", "12"],
    answer: "6",
    points: 1,
  },
  {
    id: "q-mat-02",
    subjectId: "mat",
    skill: "álgebra",
    difficulty: 2,
    type: "opcion",
    prompt: "Factoriza x² − 5x + 6.",
    options: ["(x − 2)(x − 3)", "(x − 1)(x − 6)", "(x + 2)(x + 3)", "(x − 6)(x + 1)"],
    answer: "(x − 2)(x − 3)",
    points: 2,
  },
  {
    id: "q-mat-03",
    subjectId: "mat",
    skill: "álgebra",
    difficulty: 3,
    type: "abierta",
    prompt: "Un número más el triple de su consecutivo suma 31. Plantea la ecuación y halla el número.",
    answer: "7",
    rubric: "Ecuación x + 3(x+1) = 31 → 4x + 3 = 31 → x = 7. Punto completo si plantea y resuelve.",
    points: 3,
  },
  {
    id: "q-mat-04",
    subjectId: "mat",
    skill: "geometría",
    difficulty: 1,
    type: "opcion",
    prompt: "Un triángulo tiene base 8 cm y altura 5 cm. ¿Cuál es su área?",
    options: ["20 cm²", "40 cm²", "13 cm²", "26 cm²"],
    answer: "20 cm²",
    points: 1,
  },
  {
    id: "q-mat-05",
    subjectId: "mat",
    skill: "geometría",
    difficulty: 2,
    type: "verdadero",
    prompt: "La suma de los ángulos interiores de cualquier triángulo es 180°.",
    options: ["Verdadero", "Falso"],
    answer: "Verdadero",
    points: 1,
  },
  {
    id: "q-mat-06",
    subjectId: "mat",
    skill: "estadística",
    difficulty: 1,
    type: "opcion",
    prompt: "La media de 4, 6, 8 y 10 es:",
    options: ["6", "7", "8", "28"],
    answer: "7",
    points: 1,
  },
  {
    id: "q-mat-07",
    subjectId: "mat",
    skill: "estadística",
    difficulty: 2,
    type: "opcion",
    prompt: "En el conjunto 2, 5, 5, 7, 11, la mediana es:",
    options: ["2", "5", "6", "7"],
    answer: "5",
    points: 1,
  },
  {
    id: "q-mat-08",
    subjectId: "mat",
    skill: "aritmética",
    difficulty: 1,
    type: "opcion",
    prompt: "El 25% de 80 es:",
    options: ["15", "20", "25", "40"],
    answer: "20",
    points: 1,
  },
  {
    id: "q-mat-09",
    subjectId: "mat",
    skill: "álgebra",
    difficulty: 2,
    type: "verdadero",
    prompt: "La pendiente de la recta y = −3x + 2 es negativa.",
    options: ["Verdadero", "Falso"],
    answer: "Verdadero",
    points: 1,
  },
  {
    id: "q-mat-10",
    subjectId: "mat",
    skill: "geometría",
    difficulty: 3,
    type: "abierta",
    prompt: "Un rectángulo tiene perímetro 36 cm y largo 11 cm. Calcula el ancho y el área.",
    answer: "ancho 7 cm, área 77 cm²",
    rubric: "2(l+a)=36 → a=7; área=77. Mitad de puntaje si solo halla el ancho.",
    points: 3,
  },
  {
    id: "q-len-01",
    subjectId: "len",
    skill: "gramática",
    difficulty: 1,
    type: "opcion",
    prompt: "¿Cuál oración está correctamente tildada?",
    options: [
      "El publico aplaudio al actor.",
      "El público aplaudió al actor.",
      "El publico aplaudió al actor.",
      "El público aplaudio al actor.",
    ],
    answer: "El público aplaudió al actor.",
    points: 1,
  },
  {
    id: "q-len-02",
    subjectId: "len",
    skill: "gramática",
    difficulty: 2,
    type: "opcion",
    prompt: "En «Los estudiantes, cansados, salieron», las comas encierran un:",
    options: ["Vocativo", "Inciso explicativo", "Enumeración", "Hipérbaton"],
    answer: "Inciso explicativo",
    points: 1,
  },
  {
    id: "q-len-03",
    subjectId: "len",
    skill: "comprensión",
    difficulty: 1,
    type: "verdadero",
    prompt: "La idea principal de un párrafo suele aparecer al inicio o al cierre del mismo.",
    options: ["Verdadero", "Falso"],
    answer: "Verdadero",
    points: 1,
  },
  {
    id: "q-len-04",
    subjectId: "len",
    skill: "comprensión",
    difficulty: 2,
    type: "opcion",
    prompt: "Un texto argumentativo se caracteriza sobre todo por:",
    options: [
      "Narrar una anécdota personal",
      "Defender una tesis con razones y evidencias",
      "Describir un paisaje con adjetivos",
      "Listar definiciones de un diccionario",
    ],
    answer: "Defender una tesis con razones y evidencias",
    points: 2,
  },
  {
    id: "q-len-05",
    subjectId: "len",
    skill: "redacción",
    difficulty: 2,
    type: "abierta",
    prompt: "Escribe un párrafo de 4–6 líneas que defienda por qué conviene entregar los deberes a tiempo. Incluye una tesis y dos razones.",
    answer: "Tesis + dos razones + cierre",
    rubric: "Tesis clara (1), dos razones (1), cohesión y ortografía (1).",
    points: 3,
  },
  {
    id: "q-len-06",
    subjectId: "len",
    skill: "gramática",
    difficulty: 1,
    type: "opcion",
    prompt: "El sujeto de «Llegaron tarde los invitados» es:",
    options: ["Llegaron", "tarde", "los invitados", "elíptico"],
    answer: "los invitados",
    points: 1,
  },
  {
    id: "q-len-07",
    subjectId: "len",
    skill: "comprensión",
    difficulty: 3,
    type: "abierta",
    prompt: "Lee: «No todo lo que brilla es oro, pero a veces el barro esconde pepitas.» Explica el sentido figurado en dos oraciones.",
    answer: "Las apariencias engañan; el valor puede estar en lo humilde.",
    rubric: "Identifica contraste apariencia/esencia. Puntaje parcial si parafrasea literalmente.",
    points: 3,
  },
  {
    id: "q-len-08",
    subjectId: "len",
    skill: "redacción",
    difficulty: 1,
    type: "verdadero",
    prompt: "Un conector como «sin embargo» introduce una idea de contraste.",
    options: ["Verdadero", "Falso"],
    answer: "Verdadero",
    points: 1,
  },
  {
    id: "q-ccn-01",
    subjectId: "ccn",
    skill: "célula",
    difficulty: 1,
    type: "opcion",
    prompt: "La organela que produce la mayor parte del ATP en la célula eucariota es:",
    options: ["Ribosoma", "Mitocondria", "Lisosoma", "Aparato de Golgi"],
    answer: "Mitocondria",
    points: 1,
  },
  {
    id: "q-ccn-02",
    subjectId: "ccn",
    skill: "célula",
    difficulty: 2,
    type: "verdadero",
    prompt: "Las células vegetales poseen pared celular y cloroplastos; las animales no.",
    options: ["Verdadero", "Falso"],
    answer: "Verdadero",
    points: 1,
  },
  {
    id: "q-ccn-03",
    subjectId: "ccn",
    skill: "ecosistema",
    difficulty: 1,
    type: "opcion",
    prompt: "En una cadena trófica, los productores son principalmente:",
    options: ["Herbívoros", "Hongos", "Plantas y algas", "Carnívoros"],
    answer: "Plantas y algas",
    points: 1,
  },
  {
    id: "q-ccn-04",
    subjectId: "ccn",
    skill: "ecosistema",
    difficulty: 2,
    type: "opcion",
    prompt: "Si desaparecen los depredadores tope de un bosque, lo más probable es:",
    options: [
      "Que aumenten los herbívoros y se altere la vegetación",
      "Que las plantas se reproduzcan más rápido",
      "Que el clima se vuelva más frío",
      "Que desaparezcan los descomponedores",
    ],
    answer: "Que aumenten los herbívoros y se altere la vegetación",
    points: 2,
  },
  {
    id: "q-ccn-05",
    subjectId: "ccn",
    skill: "laboratorio",
    difficulty: 2,
    type: "abierta",
    prompt: "Describe tres normas de seguridad que deben cumplirse al usar un mechero y reactivos en el laboratorio.",
    answer: "Bata, gafas, cabello recogido, no pipetear con la boca, identificar reactivos.",
    rubric: "Tres normas pertinentes y específicas del lab (1 c/u).",
    points: 3,
  },
  {
    id: "q-ccn-06",
    subjectId: "ccn",
    skill: "célula",
    difficulty: 3,
    type: "abierta",
    prompt: "Explica por qué una célula muscular tiene más mitocondrias que una célula adiposa.",
    answer: "Mayor demanda energética para la contracción.",
    rubric: "Relaciona función (contracción) con demanda de ATP y número de mitocondrias.",
    points: 3,
  },
  {
    id: "q-ccn-07",
    subjectId: "ccn",
    skill: "laboratorio",
    difficulty: 1,
    type: "verdadero",
    prompt: "La observación al microscopio requiere empezar con el objetivo de menor aumento.",
    options: ["Verdadero", "Falso"],
    answer: "Verdadero",
    points: 1,
  },
  {
    id: "q-ccn-08",
    subjectId: "ccn",
    skill: "ecosistema",
    difficulty: 1,
    type: "opcion",
    prompt: "El agua que pasa de líquido a vapor en las hojas se llama:",
    options: ["Infiltración", "Transpiración", "Condensación", "Escorrentía"],
    answer: "Transpiración",
    points: 1,
  },
  {
    id: "q-eso-01",
    subjectId: "eso",
    skill: "historia",
    difficulty: 1,
    type: "opcion",
    prompt: "La independencia del actual Ecuador se consolidó con la Batalla de Pichincha en:",
    options: ["1809", "1820", "1822", "1830"],
    answer: "1822",
    points: 1,
  },
  {
    id: "q-eso-02",
    subjectId: "eso",
    skill: "historia",
    difficulty: 2,
    type: "verdadero",
    prompt: "El 10 de agosto de 1809 se produjo el Primer Grito de Independencia en Quito.",
    options: ["Verdadero", "Falso"],
    answer: "Verdadero",
    points: 1,
  },
  {
    id: "q-eso-03",
    subjectId: "eso",
    skill: "civica",
    difficulty: 1,
    type: "opcion",
    prompt: "En el Ecuador, el organismo que vela por los derechos de niñas, niños y adolescentes en la escuela se articula con:",
    options: ["El DECE", "El SRI", "El IESS únicamente", "La Junta Mercantil"],
    answer: "El DECE",
    points: 1,
  },
  {
    id: "q-eso-04",
    subjectId: "eso",
    skill: "geografía",
    difficulty: 1,
    type: "opcion",
    prompt: "La cordillera de los Andes divide al Ecuador en regiones. La región litoral se conoce como:",
    options: ["Oriente", "Costa", "Insular", "Sierra centro"],
    answer: "Costa",
    points: 1,
  },
  {
    id: "q-eso-05",
    subjectId: "eso",
    skill: "historia",
    difficulty: 3,
    type: "abierta",
    prompt: "Compara el Primer Grito de Independencia (1809) con la Batalla de Pichincha (1822): ¿qué cambió entre ambos hitos?",
    answer: "De junta local a campaña militar bolivariana que sella la independencia.",
    rubric: "Sitúa ambos hechos, explica el cambio de alcance político-militar.",
    points: 3,
  },
  {
    id: "q-eso-06",
    subjectId: "eso",
    skill: "civica",
    difficulty: 2,
    type: "abierta",
    prompt: "Menciona dos deberes y dos derechos de un estudiante según la convivencia escolar.",
    answer: "Derechos: educación, respeto. Deberes: asistencia, respeto a pares y docentes.",
    rubric: "Dos derechos y dos deberes pertinentes (0.75 c/u, redondeo a enteros).",
    points: 3,
  },
  {
    id: "q-eso-07",
    subjectId: "eso",
    skill: "geografía",
    difficulty: 2,
    type: "verdadero",
    prompt: "Las islas Galápagos pertenecen a la región insular del Ecuador.",
    options: ["Verdadero", "Falso"],
    answer: "Verdadero",
    points: 1,
  },
  {
    id: "q-ing-01",
    subjectId: "ing",
    skill: "vocabulario",
    difficulty: 1,
    type: "opcion",
    prompt: "Choose the correct meaning of “homework”.",
    options: ["Housework", "School assignment", "Holiday", "Classroom"],
    answer: "School assignment",
    points: 1,
  },
  {
    id: "q-ing-02",
    subjectId: "ing",
    skill: "gramática",
    difficulty: 1,
    type: "opcion",
    prompt: "She ____ to school every day.",
    options: ["go", "goes", "going", "gone"],
    answer: "goes",
    points: 1,
  },
  {
    id: "q-ing-03",
    subjectId: "ing",
    skill: "gramática",
    difficulty: 2,
    type: "opcion",
    prompt: "If it rains tomorrow, we ____ the field trip.",
    options: ["cancel", "will cancel", "cancelled", "cancelling"],
    answer: "will cancel",
    points: 2,
  },
  {
    id: "q-ing-04",
    subjectId: "ing",
    skill: "comprensión",
    difficulty: 2,
    type: "verdadero",
    prompt: "“Yet” at the end of a sentence often means the action has not happened up to now.",
    options: ["Verdadero", "Falso"],
    answer: "Verdadero",
    points: 1,
  },
  {
    id: "q-ing-05",
    subjectId: "ing",
    skill: "redacción",
    difficulty: 2,
    type: "abierta",
    prompt: "Write 4 sentences about your study habits using present simple and at least one frequency adverb.",
    answer: "I always review math at night. …",
    rubric: "Cuatro oraciones (1), presente simple correcto (1), adverbio de frecuencia (1).",
    points: 3,
  },
  {
    id: "q-ing-06",
    subjectId: "ing",
    skill: "vocabulario",
    difficulty: 1,
    type: "opcion",
    prompt: "A student who did not turn in work is ____.",
    options: ["on time", "absent-minded only", "missing the deadline", "the teacher"],
    answer: "missing the deadline",
    points: 1,
  },
  {
    id: "q-ing-07",
    subjectId: "ing",
    skill: "comprensión",
    difficulty: 3,
    type: "abierta",
    prompt: "Read: “Maya reviewed her weak topics before the test and asked for extra practice.” What strategy did she use, and why does it help?",
    answer: "Targeted review of weak skills; practice retrieval improves retention.",
    rubric: "Identifica práctica deliberada / refuerzo de debilidades y da una razón.",
    points: 3,
  },
];

export function questionsForSubject(subjectId: string) {
  return BANK.filter((q) => q.subjectId === subjectId);
}
