/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as CalificacionesRouteImport } from './routes/calificaciones'
import { Route as ComunicacionesRouteImport } from './routes/comunicaciones'
import { Route as DeberesRouteImport } from './routes/deberes'
import { Route as EstudiantesRouteImport } from './routes/estudiantes'
import { Route as EvaluacionesRouteImport } from './routes/evaluaciones'
import { Route as MasRouteImport } from './routes/mas'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as DeberesIdRouteImport } from './routes/deberes_.$id'
import { Route as EstudiantesIdRouteImport } from './routes/estudiantes_.$id'
import { Route as EvaluacionesIdRouteImport } from './routes/evaluaciones_.$id'
import { Route as EvaluacionesIdRendirRouteImport } from './routes/evaluaciones_.$id_.rendir'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalificacionesRoute = CalificacionesRouteImport.update({
  id: '/calificaciones',
  path: '/calificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionesRoute = ComunicacionesRouteImport.update({
  id: '/comunicaciones',
  path: '/comunicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const DeberesRoute = DeberesRouteImport.update({
  id: '/deberes',
  path: '/deberes',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesRoute = EstudiantesRouteImport.update({
  id: '/estudiantes',
  path: '/estudiantes',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionesRoute = EvaluacionesRouteImport.update({
  id: '/evaluaciones',
  path: '/evaluaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const MasRoute = MasRouteImport.update({
  id: '/mas',
  path: '/mas',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const DeberesIdRoute = DeberesIdRouteImport.update({
  id: '/deberes_/$id',
  path: '/deberes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudiantesIdRoute = EstudiantesIdRouteImport.update({
  id: '/estudiantes_/$id',
  path: '/estudiantes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionesIdRoute = EvaluacionesIdRouteImport.update({
  id: '/evaluaciones_/$id',
  path: '/evaluaciones/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionesIdRendirRoute = EvaluacionesIdRendirRouteImport.update({
  id: '/evaluaciones_/$id_/rendir',
  path: '/evaluaciones/$id/rendir',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/calificaciones': typeof CalificacionesRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/deberes': typeof DeberesRoute
  '/estudiantes': typeof EstudiantesRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/mas': typeof MasRoute
  '/reportes': typeof ReportesRoute
  '/deberes/$id': typeof DeberesIdRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/evaluaciones/$id': typeof EvaluacionesIdRoute
  '/evaluaciones/$id/rendir': typeof EvaluacionesIdRendirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/calificaciones': typeof CalificacionesRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/deberes': typeof DeberesRoute
  '/estudiantes': typeof EstudiantesRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/mas': typeof MasRoute
  '/reportes': typeof ReportesRoute
  '/deberes/$id': typeof DeberesIdRoute
  '/estudiantes/$id': typeof EstudiantesIdRoute
  '/evaluaciones/$id': typeof EvaluacionesIdRoute
  '/evaluaciones/$id/rendir': typeof EvaluacionesIdRendirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/calificaciones': typeof CalificacionesRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/deberes': typeof DeberesRoute
  '/estudiantes': typeof EstudiantesRoute
  '/evaluaciones': typeof EvaluacionesRoute
  '/mas': typeof MasRoute
  '/reportes': typeof ReportesRoute
  '/deberes_/$id': typeof DeberesIdRoute
  '/estudiantes_/$id': typeof EstudiantesIdRoute
  '/evaluaciones_/$id': typeof EvaluacionesIdRoute
  '/evaluaciones_/$id_/rendir': typeof EvaluacionesIdRendirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/calificaciones'
    | '/comunicaciones'
    | '/deberes'
    | '/estudiantes'
    | '/evaluaciones'
    | '/mas'
    | '/reportes'
    | '/deberes/$id'
    | '/estudiantes/$id'
    | '/evaluaciones/$id'
    | '/evaluaciones/$id/rendir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/calificaciones'
    | '/comunicaciones'
    | '/deberes'
    | '/estudiantes'
    | '/evaluaciones'
    | '/mas'
    | '/reportes'
    | '/deberes/$id'
    | '/estudiantes/$id'
    | '/evaluaciones/$id'
    | '/evaluaciones/$id/rendir'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/calificaciones'
    | '/comunicaciones'
    | '/deberes'
    | '/estudiantes'
    | '/evaluaciones'
    | '/mas'
    | '/reportes'
    | '/deberes_/$id'
    | '/estudiantes_/$id'
    | '/evaluaciones_/$id'
    | '/evaluaciones_/$id_/rendir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  CalificacionesRoute: typeof CalificacionesRoute
  ComunicacionesRoute: typeof ComunicacionesRoute
  DeberesRoute: typeof DeberesRoute
  EstudiantesRoute: typeof EstudiantesRoute
  EvaluacionesRoute: typeof EvaluacionesRoute
  MasRoute: typeof MasRoute
  ReportesRoute: typeof ReportesRoute
  DeberesIdRoute: typeof DeberesIdRoute
  EstudiantesIdRoute: typeof EstudiantesIdRoute
  EvaluacionesIdRoute: typeof EvaluacionesIdRoute
  EvaluacionesIdRendirRoute: typeof EvaluacionesIdRendirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calificaciones': {
      id: '/calificaciones'
      path: '/calificaciones'
      fullPath: '/calificaciones'
      preLoaderRoute: typeof CalificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicaciones': {
      id: '/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof ComunicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deberes': {
      id: '/deberes'
      path: '/deberes'
      fullPath: '/deberes'
      preLoaderRoute: typeof DeberesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes': {
      id: '/estudiantes'
      path: '/estudiantes'
      fullPath: '/estudiantes'
      preLoaderRoute: typeof EstudiantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones': {
      id: '/evaluaciones'
      path: '/evaluaciones'
      fullPath: '/evaluaciones'
      preLoaderRoute: typeof EvaluacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mas': {
      id: '/mas'
      path: '/mas'
      fullPath: '/mas'
      preLoaderRoute: typeof MasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deberes_/$id': {
      id: '/deberes_/$id'
      path: '/deberes/$id'
      fullPath: '/deberes/$id'
      preLoaderRoute: typeof DeberesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudiantes_/$id': {
      id: '/estudiantes_/$id'
      path: '/estudiantes/$id'
      fullPath: '/estudiantes/$id'
      preLoaderRoute: typeof EstudiantesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones_/$id': {
      id: '/evaluaciones_/$id'
      path: '/evaluaciones/$id'
      fullPath: '/evaluaciones/$id'
      preLoaderRoute: typeof EvaluacionesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluaciones_/$id_/rendir': {
      id: '/evaluaciones_/$id_/rendir'
      path: '/evaluaciones/$id/rendir'
      fullPath: '/evaluaciones/$id/rendir'
      preLoaderRoute: typeof EvaluacionesIdRendirRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  CalificacionesRoute: CalificacionesRoute,
  ComunicacionesRoute: ComunicacionesRoute,
  DeberesRoute: DeberesRoute,
  EstudiantesRoute: EstudiantesRoute,
  EvaluacionesRoute: EvaluacionesRoute,
  MasRoute: MasRoute,
  ReportesRoute: ReportesRoute,
  DeberesIdRoute: DeberesIdRoute,
  EstudiantesIdRoute: EstudiantesIdRoute,
  EvaluacionesIdRoute: EvaluacionesIdRoute,
  EvaluacionesIdRendirRoute: EvaluacionesIdRendirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
